
import type { ClassifyCallOutput } from "@/ai/flows/classify-call";

// Represents the data structure for a call record stored in Firestore (or similar)
export interface CallRecord extends ClassifyCallOutput {
  id: string;         // Unique ID, typically generated by Firestore
  date: string;       // ISO string format of creation/occurrence time, from Firestore serverTimestamp
  transcript: string;
  summary?: string;
}

// Payload for creating/saving a new call record. 'id' and 'date' are omitted as they are backend-generated.
export type SaveCallPayload = Omit<CallRecord, 'id' | 'date'>;


export type CallNature = "Ocorrência" | "Incidente";

    